version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXTAUTH_SECRET=secret
      - NEXTAUTH_URL=http://localhost:3000
      - API_URL=http://localhost:8000/api/v1
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api/v1
